name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - run: npm install -g @quasar/cli
      - run: npm install
      - run: quasar build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/spa
      - run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -X PATCH \
          -d '{"custom_domain": "gharbidev.com"}' \
          https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/pages
